region             = "eu-central"
k3s_token          = "un-token-random-generado"
server_type        = "cax11"
name_prefix        = "nakamalabsio"
cluster_name       = "k3s-tutorial"
location           = "nbg1"